### ISSUE TITLE
ImportError: DLL load failed: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by imran110219** [imran110219/Natural_Language_Processing#1]
I am getting this error while running jupyter notebook.

> H:\Research\NLP\NLP Task 1>jupyter notebook
Traceback (most recent call last):
  File "C:\Users\Imran\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 18, in <module>
    from urllib.request import urlretrieve
  File "C:\Users\Imran\AppData\Local\Programs\Python\Python36-32\Lib\urllib\request.py", line 88, in <module>
    import http.client
  File "C:\Users\Imran\AppData\Local\Programs\Python\Python36-32\Lib\http\client.py", line 71, in <module>
    import email.parser
  File "C:\Users\Imran\AppData\Local\Programs\Python\Python36-32\Lib\email\parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "C:\Users\Imran\AppData\Local\Programs\Python\Python36-32\Lib\email\feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "C:\Users\Imran\AppData\Local\Programs\Python\Python36-32\Lib\email\_policybase.py", line 9, in <module>
    from email.utils import _has_surrogates
  File "C:\Users\Imran\AppData\Local\Programs\Python\Python36-32\Lib\email\utils.py", line 29, in <module>
    import socket
  File "C:\Users\Imran\AppData\Local\Programs\Python\Python36-32\Lib\socket.py", line 49, in <module>
    import _socket
ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by imran110219** [comment]
1. Uninstall python and anaconda.
2. Reinstall again.
